//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustFood.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailedSale
    {
        public long DetailedSaleID { get; set; }
        public int SaleID { get; set; }
        public int CategoryID { get; set; }
        public int SellingPrice { get; set; }
        public Nullable<int> Discount { get; set; }
        public string Note { get; set; }
        public int SoldAt { get; set; }
        public System.DateTime Time { get; set; }
        public int UserID { get; set; }
        public bool IsDiscard { get; set; }
        public bool IsMarkedDiscard { get; set; }
        public string DiscountPerson { get; set; }
        public string DiscountNumber { get; set; }
        public short Qty { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Sale Sale { get; set; }
        public virtual User User { get; set; }
    }
}
