//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustFood.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public int InventoryID { get; set; }
        public int CategoryID { get; set; }
        public double Quantity { get; set; }
        public int LastEditedby { get; set; }
        public double SoldPrice { get; set; }
        public byte QtyType { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual QuantityType QuantityType { get; set; }
        public virtual User User { get; set; }
    }
}
