//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustFood.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryOutConfig
    {
        public int InventoryOutConfigID { get; set; }
        public int CategoryID { get; set; }
        public int DiscardItemCategory { get; set; }
        public decimal PerSaleQuantity { get; set; }
        public byte QtyType { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Category Category1 { get; set; }
        public virtual QuantityType QuantityType { get; set; }
    }
}
