//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustFood.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuantityConversation
    {
        public byte QuantityConversationID { get; set; }
        public byte QuantityTypeID { get; set; }
        public byte ConvertedTypeID { get; set; }
        public decimal Difference { get; set; }
    
        public virtual QuantityType QuantityType { get; set; }
        public virtual QuantityType QuantityType1 { get; set; }
    }
}
