//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustFood.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewSummaryAccountBalance
    {
        public string AccountOfLog { get; set; }
        public string AccountOfName { get; set; }
        public Nullable<double> Balance { get; set; }
        public Nullable<int> AccountOf { get; set; }
    }
}
