//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustFood.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountBalance
    {
        public long AccountBalanceID { get; set; }
        public System.DateTime Dated { get; set; }
        public double Amount { get; set; }
        public bool IsBoughtProduct { get; set; }
        public Nullable<int> CategoryProduct { get; set; }
        public Nullable<decimal> AddedQuantity { get; set; }
        public bool IsExpense { get; set; }
        public bool IsAddedMoney { get; set; }
        public Nullable<int> AccountOf { get; set; }
        public int AddBy { get; set; }
        public string Note { get; set; }
        public bool IsVerified { get; set; }
        public Nullable<byte> QtyType { get; set; }
        public bool IsDailyExpense { get; set; }
        public bool IsRevenueOfDailySales { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual QuantityType QuantityType { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
