//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustFood.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Config
    {
        public bool ConfigID { get; set; }
        public bool IsNotifyDeveloperOnError { get; set; }
        public bool IsNotifyAdminOnError { get; set; }
        public string GeneralNotificationMail { get; set; }
        public string DeveloperEmail { get; set; }
        public string AdminEmail { get; set; }
        public bool OnMistakeNotifyAllAdmins { get; set; }
        public string CompanyName { get; set; }
        public string CompanyEmail { get; set; }
        public string CompanyContacts { get; set; }
        public short DefaultTimeZoneID { get; set; }
        public string ApplicationName { get; set; }
        public string ApplicationSubtitle { get; set; }
    
        public virtual TimeZone TimeZone { get; set; }
    }
}
