//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustFood.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryIn
    {
        public long InventoryInID { get; set; }
        public int CategoryID { get; set; }
        public decimal Quantity { get; set; }
        public double UnitPrice { get; set; }
        public int AddedBy { get; set; }
        public bool IsAddedBySelling { get; set; }
        public byte QtyType { get; set; }
        public System.DateTime Dated { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual QuantityType QuantityType { get; set; }
        public virtual User User { get; set; }
    }
}
