//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustFood.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalaryPaid
    {
        public long SalaryPaidID { get; set; }
        public int UserID { get; set; }
        public System.DateTime SalaryOfDated { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> Year { get; set; }
        public double Paid { get; set; }
        public double Salary { get; set; }
        public System.DateTime PaidDate { get; set; }
    
        public virtual User User { get; set; }
    }
}
