//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustFood.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewInventoryIn
    {
        public int CategoryID { get; set; }
        public Nullable<decimal> InventoryInQuantity { get; set; }
        public Nullable<double> InventoryInUnitPrice { get; set; }
        public string Category { get; set; }
    }
}
