//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustFood.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationSeen
    {
        public System.Guid NotificationSeenID { get; set; }
        public long NotificationID { get; set; }
        public int UserID { get; set; }
        public System.DateTime SeenAt { get; set; }
        public bool IsSeen { get; set; }
    
        public virtual Notification Notification { get; set; }
        public virtual User User { get; set; }
    }
}
