//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustFood.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeZone
    {
        public TimeZone()
        {
            this.Configs = new HashSet<Config>();
            this.Users = new HashSet<User>();
        }
    
        public short TimeZoneID { get; set; }
        public string TimeZoneInfoId { get; set; }
        public string TimeZoneDisplay { get; set; }


        public virtual ICollection<Config> Configs { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
